packages:
  - .
  - docs
autoInstallPeers: false
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  ember-lifeline: patches/ember-lifeline.patch
resolvePeersFromWorkspaceRoot: false

ignoreWorkspaceRootCheck: true
